Add files via upload
Verjot002/InnovateWab_landing_page pull request #2
Opened 2024-12-24 09:44 UTC by Verjot002

InnovateWeb_landing page

2024-12-25 02:30 UTC, ms-tech-geek-dml commented
**JavaScript Fixes Needed**

- Missing mobile menu close when clicking outside
- No form validation regex for email
- No error handling

2024-12-25 02:30 UTC, ms-tech-geek-dml requested changes

2024-12-25 02:30 UTC, ms-tech-geek-dml commented on home.html
> +  <meta name="viewport" content="width=device-width, initial-scale=1.0">
Add meta description and keywords

2024-12-25 02:30 UTC, ms-tech-geek-dml commented on home.html
> +        <i class="fas fa-desktop"></i>
Missing ARIA labels for icons

2024-12-25 02:30 UTC, ms-tech-geek-dml commented on home.html
> +      <input type="text" placeholder="Your Name" required>
- Form inputs missing proper IDs and labels

2024-12-25 02:30 UTC, ms-tech-geek-dml commented on styles.css
> +      top: 60px;
```
@media (max-width: 768px) {
    .nav-links {
        /* Causes layout shift */
        top: 60px;
    }
}
```

2024-12-30 12:26 UTC, sumitkumar797 approved these changes

2025-01-03 09:13 UTC, merged